events { }

http {
    upstream servidores {
        # Balanceo por pesos:
        # servidor1 recibe 50% del tráfico (peso 5)
        # servidor2 recibe 30% del tráfico (peso 3)
        # servidor3 recibe 20% del tráfico (peso 2)
        server servidor1:5000 weight=5;
        server servidor2:5000 weight=3;
        server servidor3:5000 weight=2;
    }

    server {
        listen 80;

        location / {
            proxy_pass         http://servidores;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        }
    }
}
